spring:
  datasource:
    url: jdbc:mysql://arcard.clhudn7mqzey.us-east-2.rds.amazonaws.com:3306/arcard?sslmode=require
    username: root
    password: ArCard35142
#    driver-class-name: com.mysql.cj.jdbc.Driver

#    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS DOCSPRESS
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

  flyway:
    baseline-on-migrate: true

  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
#      ddl-auto: update
      ddl-auto: validate
    properties:
      hibernate:
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 50MB
      max-request-size: 55MB

file:
  upload-dir: ./QrImage

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000


server:
  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store: /etc/letsencrypt/live/core.getamaterasu.com/keystore.p12
    key-store-password: ArCard132$
    key-alias: tomcat



